server:
  port: 9090

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/accounts/**
        - id: movement-service
          uri: lb://account-service
          predicates:
            - Path=/api/movements/**